<?php

namespace App\Repositories\Core;

use App\Models\Profile;
use App\Repositories\Core\BaseRepository;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;

class ProfileRepository extends BaseRepository {
    public function __construct(private readonly Profile $profile)
    {
        parent::__construct($profile);
    }

    function getEntity() {}

    public function getAll(): Collection
    {
        return $this->profile->all();
    }

    public function findWhere(string $column, string $value): Collection
    {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }

    public function paginate(int $totalPage = 10): LengthAwarePaginator
    {
        return parent::paginate($totalPage); // TODO: Change the autogenerated stub
    }


}