<?php


namespace App\Repositories\Core;
use App\Exceptions\CredentialsException;
use App\Models\Apartment;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\DB;
use \Illuminate\Database\Eloquent\Collection;

class ApartmentRepository extends BaseRepository {
    public function __construct(private Apartment $apart) {
        parent::__construct($apart);
    }

    /**
     * Summary of getAll
     * @return Apartment[]|Collection|Collection<int, Apartment>
     */
    public function getAll(): Collection
    {
        return $this->apart->all();
    }

    /**
     * Summary of findWhere
     * @param string $column
     * @param string $value
     * @return Collection
     */
    public function findWhere(string $column, string $value): Collection
    {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of paginate
     * @param int $totalPage
     * @return LengthAwarePaginator|\Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public function paginate(int $totalPage = 10): LengthAwarePaginator
    {
        return parent::paginate($totalPage); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of getTowerApartment
     * @param int $id
     */
    public function getTowerApartment(int $id) {
        $dados = $this->loadRelationships($this->apart, ['tower'])->where('tower_id', $id)->get();
        return $dados;
    }

    /**
     * Summary of store
     * @param array $data
     * @throws \App\Exceptions\CredentialsException
     * @return void
     */
    public function store(array $data): void
    {
        try {
            DB::beginTransaction();
            $this->apart->create($data);
            DB::commit();
        } catch (\Exception $th) {
            DB::rollback();
            throw new CredentialsException($th->getMessage());
        }
    }

    /**
     * Summary of loadRelationships
     * @param mixed $query
     * @param mixed $relationships
     */
    private function loadRelationships($query, $relationships = [])
    {

        return $query->with(
            $relationships
        );
    }

}
