<?php


namespace App\Repositories\Core;

use App\Models\Apartment;
use App\Models\Condominium;
use App\Models\Company;
use App\Models\TypeService;
use App\Models\Tower;
use App\Repositories\Core\BaseRepository;
use App\Exceptions\CredentialsException;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;

class CondominiumRepository extends  BaseRepository {

    private $tower;
    private $ap;

    public function __construct(private Condominium $condominium) {
        parent::__construct($condominium);
        $this->tower = new Tower();
        $this->ap = new Apartment();
    }

    /**
     * Summary of getAll
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getAll(): Collection {
        return $this->condominium->all();
    }

    /**
     * Summary of findWhere
     * @param string $column
     * @param string $value
     * @return Collection
     */
    public function findWhere(string $column, string $value): Collection
    {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of findByName
     * @param string $value
     * @return Condominium|object|\Illuminate\Database\Eloquent\Model|null
     */
    public function findByName(string $value) {
        return $this->condominium->where('name', $value)->first();
    }

    /**
     * Summary of paginate
     * @param int $totalPage
     * @return LengthAwarePaginator|mixed
     */
    public function paginate(int $totalPage = 10): LengthAwarePaginator
    {
        return parent::paginate($totalPage); // TODO: Change the autogenerated stub
    }

    /**
     * antes de criar condominio
     * verificar o padrão nome torres
     * listar de acordo e salvar a torre na base de dados
     * dividir a quantidade pelas torres pra saber capacidade de APs por torres.
     */

    public function store(array $data)
    {
        try {
            DB::beginTransaction();
            $cnpj = preg_replace('/[^0-9]/', '', $data['cnpj']);
            $telefone = $data['phone'] ? preg_replace('/[^0-9]/', '', $data['phone']) : null;
            $email = $data['email'] ?? null;
            $responsible_name = $data['responsible_name'] ?? null;
            $observation = $data['observation'] ?? 'Empresa é o condomínio ';

            # APENAS PARA CRIAR A EMPRESA DO TIPO CONDOMINIO PRÓPRIO
            unset($data['cnpj']);
            unset($data['phone']);
            unset($data['email']);
            unset($data['responsible_name']);
            unset($data['observation']);

            $condominium = $this->condominium->create($data);

            if (isset($data['qtd_tower'])) {
                $div_tower_ap = (intval($data['qtd_ap']) / intval($data['qtd_tower']));
                # ex: 272 / 2 = 136

                for($i = 1; $i <= intval($data['qtd_tower']); $i++) {
                    # capacidade da torre
                    # qtd torre * quantidade andar

                   $this->tower->create([
                        'name' => $data['tower_type'] . $i,
                        'capacity' => round($div_tower_ap),
                        'type' => $data['tower_type'],
                        'condominium_id' => $condominium->id
                    ]);
                }
            }

            /**
             * Criar empresa do tipo condomínio próprio
             */
            Company::create([
                'isActive' => true,
                'responsible_name' => $responsible_name,
                'observation' => $observation,
                'phone' => $telefone,
                'email' => $email,
                'type_service_id' => TypeService::where('slug','condominio_proprio')->first()->id,
                'cnpj' => $cnpj,
                'name_company' => $data['name'],
                'condominium_id' => $condominium->id
            ]);

            DB::commit();
        } catch (\Exception $th) {
            \Log::error('Erro ao cadastrar condomínio: '.$th->getMessage());
            DB::rollback();
            throw new CredentialsException($th->getMessage());
        }
    }


    /**
     * Summary of applyFilter
     * @param array $items
     */
    public function applyFilter(array $items)
    {
        $relationship = $this->condominium;

        foreach ($items as $key => $value) {
            if ($value) {
                if (in_array($key, ['name', 'address','city','qtd_tower','qtd_ap'])) {
                    if ($key == 'name') {
                        $relationship->whereRaw("UPPER(condominium.name) like UPPER('%{$value}%')");
                    }
                    if ($key == 'address') {
                        $relationship->whereRaw("UPPER(condominium.address) like UPPER('%{$value}%')");
                    }
                    if ($key == 'city') {
                        $relationship->whereRaw("UPPER(condominium.city) like UPPER('%{$value}%')");
                    }
                    if ($key == 'qtd_tower') {
                        $relationship->where("condominium.qtd_tower", $value);
                    }
                    if ($key == 'qtd_ap') {
                        $relationship->where("condominium.qtd_ap", $value);
                    }
                }
            }
        }

        $totalPage = 10;
        return $relationship->orderBy('condominium.name')->paginate($totalPage);
    }

    /**
     * Esse store é para o filament usar
     * @param array $data
     * @throws \DomainException
     * @return Condominium
     */
    public function storeForAdmin(array $data): Condominium
{
    try {
        DB::beginTransaction();
         $cnpj = preg_replace('/[^0-9]/', '', $data['cnpj']);
            $telefone = $data['phone'] ? preg_replace('/[^0-9]/', '', $data['phone']) : null;
            $email = $data['email'] ?? null;
            $responsible_name = $data['responsible_name'] ?? null;
            $observation = $data['observation'] ?? 'Empresa é o condomínio ';

            # APENAS PARA CRIAR A EMPRESA DO TIPO CONDOMINIO PRÓPRIO
            unset($data['cnpj']);
            unset($data['phone']);
            unset($data['email']);
            unset($data['responsible_name']);
            unset($data['observation']);
        $condominium = $this->condominium->create($data);

        if (isset($data['qtd_tower'])) {
            $div_tower_ap = (intval($data['qtd_ap']) / intval($data['qtd_tower']));

            for ($i = 1; $i < intval($data['qtd_tower']); $i++) {
                $this->tower->create([
                    'name' => 'Torre ' . $i,
                    'capacity' => round($div_tower_ap),
                    'type' => 1,
                    'condominium_id' => $condominium->id
                ]);
            }
        }

         /**
             * Criar empresa do tipo condomínio próprio
             */
            Company::updateOrCreate([
                'condominium_id' => $condominium->id,
                'cnpj' => $cnpj
            ], [
                'isActive' => true,
                'responsible_name' => $responsible_name,
                'observation' => $observation,
                'phone' => $telefone,
                'email' => $email,
                'type_service_id' => TypeService::where('slug','condominio_proprio')->first()->id,
                'cnpj' => $cnpj,
                'name_company' => $data['name'],
                'condominium_id' => $condominium->id
            ]);

        DB::commit();

        return $condominium->refresh();

    } catch (\Exception $th) {
        DB::rollback();
        throw new \DomainException($th->getMessage());
    }

}

public function update($model, array $data)
{
    try {
        DB::beginTransaction();

        $updatedCondominium = $model->update($data);
        $cnpj = preg_replace('/[^0-9]/', '', $data['cnpj']);
            $telefone = $data['phone'] ? preg_replace('/[^0-9]/', '', $data['phone']) : null;
            $email = $data['email'] ?? null;
            $responsible_name = $data['responsible_name'] ?? null;
            $observation = $data['observation'] ?? 'Empresa é o condomínio ';
            # APENAS PARA ATUALIZAR A EMPRESA DO TIPO CONDOMINIO PRÓPRIO
            unset($data['cnpj']);
            unset($data['phone']);
            unset($data['email']);
            unset($data['responsible_name']);
            unset($data['observation']);

            /**
             * Criar empresa do tipo condomínio próprio
             */
            Company::updateOrCreate([
                'condominium_id' => $updatedCondominium->id,
                'cnpj' => $cnpj
            ], [
                'isActive' => true,
                'responsible_name' => $responsible_name,
                'observation' => $observation,
                'phone' => $telefone,
                'email' => $email,
                'type_service_id' => TypeService::where('slug','condominio_proprio')->first()->id,
                'cnpj' => $cnpj,
                'name_company' => $data['name'],
                'condominium_id' => $updatedCondominium->id
            ]);
        DB::commit();

    } catch (\Exception $th) {
        DB::rollback();
        throw new \DomainException($th->getMessage());
    }
    // return $model->update($data);
}

 /**
  * Summary of updateForAdmin para o filament
  * @param mixed $model
  * @param array $data
  */
 public function updateForAdmin($model, array $data)
    {
        try {
            DB::beginTransaction();
            $cnpj = preg_replace('/[^0-9]/', '', $data['cnpj']);
            $telefone = $data['phone'] ? preg_replace('/[^0-9]/', '', $data['phone']) : null;
            $email = $data['email'] ?? null;
            $responsible_name = $data['responsible_name'] ?? null;
            $observation = $data['observation'] ?? 'Empresa é o condomínio ';
            # APENAS PARA ATUALIZAR A EMPRESA DO TIPO CONDOMINIO PRÓPRIO
            unset($data['cnpj']);
            unset($data['phone']);
            unset($data['email']);
            unset($data['responsible_name']);
            unset($data['observation']);

            $updatedCondominium = $model->update($data);

            /**
             * Criar empresa do tipo condomínio próprio
             */
            Company::updateOrCreate([
                'condominium_id' => $updatedCondominium->id,
                'cnpj' => $cnpj
            ], [
                'isActive' => true,
                'responsible_name' => $responsible_name,
                'observation' => $observation,
                'phone' => $telefone,
                'email' => $email,
                'type_service_id' => TypeService::where('slug','condominio_proprio')->first()->id,
                'cnpj' => $cnpj,
                'name_company' => $data['name'],
                'condominium_id' => $updatedCondominium->id
            ]);

            DB::commit();

            return $updatedCondominium->refresh();
        } catch (\Exception $th) {
            DB::rollback();
            throw new \DomainException($th->getMessage());;
        }
    }


}
