<?php


namespace App\Repositories\Core;

use App\Models\Drive;
use App\Repositories\Core\BaseRepository;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;


class DriveRepository extends  BaseRepository {

    /**
     * Summary of __construct
     * @param \App\Models\Drive $drive
     */
    public function __construct(private Drive $drive)
    {
        parent::__construct($drive);
    }

    function getEntity() {}

    /**
     * Summary of getAll
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getAll(): Collection
    {
        return $this->relationship($this->drive, ['resident'])->get();
    }

    /**
     * Summary of findWhere
     * @param string $column
     * @param string $value
     * @return Collection
     */
    public function findWhere(string $column, string $value): Collection
    {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of paginate
     * @param int $totalPage
     * @return LengthAwarePaginator|\Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public function paginate(int $totalPage = 10): LengthAwarePaginator
    {
        return parent::paginate($totalPage); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of applyFilter
     * @param array $items
     * @return void
     */
    public function applyFilter(array $items)
    {
        $relationship = $this->drive;

        foreach ($items as $key => $value) {
            if ($value) {
                if (in_array($key, ['description', 'plate_number','model','color'])) {
                    if ($key == 'description') {
                        $relationship->whereRaw("UPPER(drive.description) like UPPER('%{$value}%')");
                    }
                    if ($key == 'plate_number') {
                        $relationship->whereRaw("UPPER(drive.plate_number) like UPPER('%{$value}%')");
                    }
                    if ($key == 'model') {
                        $relationship->whereRaw("UPPER(drive.model) like UPPER('%{$value}%')");
                    }
                    if ($key == 'color') {
                        $relationship->whereRaw("UPPER(drive.color) like UPPER('%{$value}%')");
                    }

                }
            }
        }
    }


    private function relationship($entity, $relations = []) {
        return $entity->with($relations);
    }

}
