<?php


namespace App\Repositories\Core;

use App\Models\Occurrence;
use App\Models\StatusOccurrence;
use App\Models\StatusPriority;
use App\Models\ResponsibleAtribuiton;
use App\Models\TypeOccurrence;
use App\Models\HistoricOccurrence;
use App\Models\Resident;
use App\Models\Fines;
use App\Exceptions\CredentialsException;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
class OccurrentRepository extends BaseRepository {



    /**
     * Summary of __construct
     * @param \App\Models\Occurrence $occurrence
     */
    public function __construct(private Occurrence $occurrence){
            parent::__construct($occurrence);
    }

    function getEntity()  {

    }

    /**
     * Summary of getAll
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getAll(): Collection
    {
        // return $this->occurrence->all();
        return $this->loadRelationships($this->occurrence, ['user','typeOccurrence','statusOcurrence','statusPriority'])->get();
    }

    /**
     * Summary of findById
     * @param mixed $id
     * @return object
     */
    public function findById($id): object {

        return $this->loadRelationships($this->occurrence, ['user','typeOccurrence','statusOcurrence','statusPriority'])->where('id', $id)->first();
    }

    /**
     * Summary of findWhere
     * @param string $column
     * @param string $value
     * @return Collection
     */
    public function findWhere(string $column, string $value): Collection
    {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of paginate
     * @param int $totalPage
     * @return LengthAwarePaginator|\Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public function paginate(int $totalPage = 10): LengthAwarePaginator
    {
        return parent::paginate($totalPage); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of storeFine
     * @param array $data
     * @throws \App\Exceptions\CredentialsException
     *
     */
    public function storeFine(array $data)
    {
        try {
            DB::beginTransaction();
            $fine = Fines::create($data);
            DB::commit();
        } catch (\Exception $th) {
            DB::rollback();
            throw new CredentialsException($th->getMessage());
        }
        return $fine;
    }
    /**
     * Summary of store
     * @param array $data
     * @throws \App\Exceptions\CredentialsException
     *
     */
    public function storeModel(array $data)
    {
        try {
            DB::beginTransaction();
            $ocurrence = $this->occurrence->create($data['occurrence']);

            // valida resp caso seja admin
            if (isset($data['responsible_id']) && !empty($data['responsible_id'])) {
                ResponsibleAtribuiton::updateOrCreate([
                    'occurrence_id'=> $ocurrence->id,
                    'responsible_id' => $data['responsible_id'],
                    'status_occurrence_id' => $data['occurrence']['status_occurrence_id']]);
            }
            DB::commit();
        } catch (\Exception $th) {
            DB::rollback();
            throw new CredentialsException($th->getMessage());
        }
        return $ocurrence;
    }


    /**
     * Summary of applyFilter
     * @param array $items
     */
    public function applyFilter(array $items)
    {
        $relationship = $this->loadRelationships($this->occurrence, ['user']);

        foreach ($items as $key => $value) {
            if ($value) {
                if (in_array($key, ['title','user_id','type_occurrence_id','isResolved','resolution'])) {
                    if ($key == 'title') {
                        $relationship->whereRaw("UPPER(occurrence.title) like UPPER('%{$value}%')");
                    }
                    if ($key == 'type_occurrence_id') {
                        $relationship->where("occurrence.type_occurrence_id", $value);
                    }
                    if ($key == 'isResolved') {
                        $relationship->where("occurrence.isResolved", $value);
                    }
                    if ($key == 'user_id') {
                        $relationship->where("occurrence.user_id", $value);
                    }
                }
            }
        }

        return $relationship->orderBy('date_occurrence')->get();
    }


    /**
     * Summary of loadRelationships
     * @param mixed $query
     * @param mixed $relationships
     */
    private function loadRelationships($query, $relationships = [])
    {
        return $query->with(
            $relationships
        );
    }

    /**
     * Summary of typeOccurrence
     */
    public function typeOccurrence() {
        return TypeOccurrence::select('id','description')->get();
    }

    /**
     * Summary of statusOccurrence
     * @param mixed $slug
     * @return Collection<int, StatusOccurrence>|StatusOccurrence|StatusOccurrence[]|TValue|null
     */
    public function statusOccurrence($slug = '') {
        if (!empty($slug)) {
            return StatusOccurrence::where('slug','=', $slug)->first();
        }
        return StatusOccurrence::get();
    }

    /**
     * Summary of statusPriority
     * @param mixed $slug
     * @return Collection<int, StatusPriority>|StatusPriority|StatusPriority[]|TValue|null
     */
    public function statusPriority($slug = '') {
        if (!empty($slug)) {
            return StatusPriority::where('slug','=', $slug)->first();
        }
        return StatusPriority::get();
    }

    /**
     * Summary of getResident
     * @param int $id
     * @return Resident|TValue|null
     */
    public function getResident(int $id) {
        return Resident::where('user_id','=',$id)->first();
    }

    /**
     * Summary of storeHistoric
     * Salvando histórico de observações de ocorrencias
     * @param mixed $array
     * @return void
     */
    public function storeHistoric($array) {

        $data = ['observations' => $array['data']['observations'], 'occurrence_id' => $array['data']['id']];
        $occurrence = $this->occurrence->where('id', $array['data']['id'])->first();
        DB::beginTransaction();
        try {
            HistoricOccurrence::create($data);
            $occurrence->isResolved = true;
            $occurrence->save();
            DB::commit();

        } catch (\Exception $ex) {
            DB::rollBack();
            Log::error('Erro ao inserir histórico: ', [$ex->getMessage()]);

        }
    }

    /**
     * Summary of responsibleAtrbuition
     * @param array $data
     * @return void
     */
    public function responsibleAtrbuition(array $data) {
        ResponsibleAtribuiton::updateOrCreate([
                    'occurrence_id'=> $data['occurrence_id'],
                    'responsible_id' => $data['users_id'],
                    'status_occurrence_id' => $data['status_occurrence_id']]);
    }

    /**
     * Summary of update
     * @param object $entity
     * @param array $data
     * @return void
     */
    public function update(object $entity, array $data) {

        $entity->update($data);
    }



    /**
     * Quantidade de ocorrências por morador
     * @param int $residentId
     * @return int
     */
    public function getCountOccurrencesByResident(int $residentId) {
        return $this->occurrence->where('resident_id', $residentId)->count();
    }



}

