<?php


namespace App\Repositories\Core;

use App\Models\Peoples;
use App\Models\DrivePeople;
use App\Models\BankAccount;
use App\Models\Employee;
use App\Models\EmployeePeople;
use App\Models\TypeAccount;
use App\Exceptions\CredentialsException;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use App\Models\Drive;

class PeoplesRepository extends BaseRepository
{


    public function __construct(private Peoples $entity)
    {
        parent::__construct($entity);
    }

    /**
     * Summary of getAll
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getAll(): Collection
    {
        return $this->relationship($this->entity, ['drive', 'bank', 'employeer'])->get();
    }

    /**
     * Summary of findWhere
     * @param string $column
     * @param string $value
     * @return Collection
     */
    public function findWhere(string $column, string $value): Collection
    {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of paginate
     * @param int $totalPage
     * @return \Illuminate\Pagination\LengthAwarePaginator
     */
    public function paginate(int $totalPage = 10): LengthAwarePaginator
    {
        return parent::paginate($totalPage); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of findById
     * @param int $id
     * @return object
     */
    public function findById(int $id): object
    {
        return $this->relationship($this->entity, ['drive', 'bank', 'employeer'])->findOrFail($id);
    }


    /**
     * Summary of getEmailPeople
     * @param string $email
     */
    public function getEmailPeople(string $email)
    {
        return $this->relationship($this->entity, ['drive'])->where('email', '=', $email)->get();
    }

    /**
     * Summary of relationship
     * @param mixed $entity
     * @param mixed $relations
     */
    private function relationship($entity, $relations = [])
    {

        return $entity->with($relations);
    }

    /**
     * Summary of getTypeAccount
     * @return Collection|TypeAccount[]
     */
    public function getTypeAccount()
    {
        return TypeAccount::get();
    }

    /**
     * Summary of storeFormData
     * @param array $data
     * @return void
     */
    public function storeFormData(array $data)
    {
        try {
            DB::beginTransaction();
            $people = $this->entity->create($data['people']);
            $data['people_id'] = $people->id;
            if (isset($data['drive']) && !empty($data['drive']['description'])) {
                $this->createDrive($data);
            }
            if (isset($data['bank']) && !empty($data['bank']['banck_accont_code'])) {
                $data['bank']['people_id'] = $people->id;
                $this->createBankAccount($data['bank']);
            }
            if (isset($data['employee']) && !empty($data['employee']['name'])) {
                $this->createEmployeer($data);
            }
            DB::commit();
        } catch (\Exception $th) {
            DB::rollBack();
            \Log::error('Erro ao salvar os dados', [$th->getMessage()]);
        }

    }

    /**
     * Summary of updateFormData
     * @param object $entity
     * @param array $data
     * @return void
     */
    public function updateFormData(object $entity, array $data)
    {
        try {
            DB::beginTransaction();
            $entity->update($data['people']);
            $data['people_id'] = $entity->id;
            if (isset($data['drive']) && !empty($data['drive']['description'])) {
                $this->createDrive($data);
            }
            if (isset($data['bank']) && !empty($data['bank']['banck_accont_code'])) {
                $data['bank']['people_id'] = $entity->id;
                $this->createBankAccount($data['bank']);
            }
            if (isset($data['employee']) && !empty($data['employee']['name'])) {
                $this->createEmployeer($data);
            }

            DB::commit();
        } catch (\Exception $th) {
            DB::rollBack();
            \Log::error('Erro ao salvar os dados', [$th->getMessage()]);
        }
    }

    /**
     * Summary of createDrive
     * @param mixed $drives
     * @return void
     */
    private function createDrive($drives)
    {
        $drive = Drive::updateOrCreate($drives['drive']);
        DrivePeople::updateOrCreate(
            [
                'drive_id' => $drive->id,
                'people_id' => $drives['people_id']
            ]
        );
    }

    /**
     * Summary of createBankAccount
     * @param mixed $account
     * @return void
     */
    private function createBankAccount($account)
    {
        BankAccount::updateOrCreate($account);
    }

    /**
     * Summary of createEmployeer
     * @param mixed $employee
     * @return void
     */
    private function createEmployeer($employee)
    {
        $employees = Employee::updateOrCreate($employee['employee']);
        EmployeePeople::updateOrCreate([
            'employee_id' => $employees->id,
            'people_id' => $employee['people_id']
        ]);
    }

    /**
     * Summary of getPeopleCpf
     * @param string $cpf
     */
    public function getPeopleCpf(string $cpf)
    {

        return $this->relationship($this->entity, ['drive'])->where('cpf', '=', $cpf)->first();
    }


    public function applyFilter(array $data)
    {

        $relationship = $this->relationship($this->entity, ['bank', 'drive']);

        foreach ($data['people'] as $key => $value) {
            if ($value) {
                if (in_array($key, ['email', 'cpf', 'rg'])) {
                    if ($key == 'email') {
                        $relationship->whereRaw("UPPER(peoples.name) like UPPER('%{$value}%')");
                    }
                    if ($key == 'cpf') {
                        $relationship->whereRaw("UPPER(peoples.cpf) like UPPER('%{$value}%')");
                    }
                    if ($key == 'rg') {
                        $relationship->whereRaw("UPPER(peoples.rg) like UPPER('%{$value}%')");
                    }
                }
            }

        }
        $totalPage = 10;
        return $relationship->orderBy('peoples.name')->paginate($totalPage);
    }



    /**
     * Summary of storeFormDataForAdmin para o filament
     * @param array $data
     * @return Peoples|\Illuminate\Database\Eloquent\Model
     */
    public function storeFormDataForAdmin(array $data)
    {
        try {
            DB::beginTransaction();

            $people = $this->entity->create($data['people']);

            if (!empty($data['drive']['description'] ?? null)) {
                $data['drive']['people_id'] = $people->id;
                $this->createDrive($data);
            }

            if (!empty($data['bank']['banck_accont_code'] ?? null)) {
                $data['bank']['people_id'] = $people->id;
                $this->createBankAccount($data['bank']);
            }

            if (!empty($data['employee']['name'] ?? null)) {
                $data['employee']['people_id'] = $people->id;
                $this->createEmployeer($data);
            }

            DB::commit();
            return $people;

        } catch (\Exception $th) {
            DB::rollBack();
            throw $th;
        }
    }

    public function updateForAdmin(object $entity, array $data)
    {
        try {
            DB::beginTransaction();
            $entity->update($data['people']);
            $data['people_id'] = $entity->id;
            if (isset($data['drive']) && !empty($data['drive']['description'])) {
                $this->createDrive($data);
            }
            if (isset($data['bank']) && !empty($data['bank']['banck_accont_code'])) {
                $data['bank']['people_id'] = $entity->id;
                $this->createBankAccount($data['bank']);
            }
            if (isset($data['employee']) && !empty($data['employee']['name'])) {
                $this->createEmployeer($data);
            }

            DB::commit();

            return $entity;
        } catch (\Exception $th) {
            DB::rollBack();
            \Log::error('Erro ao salvar os dados', [$th->getMessage()]);
            throw $th;
        }
    }

}
