<?php


namespace App\Repositories\Core;

use App\Models\Peoples;
use App\Models\DrivePeople;
use App\Exceptions\CredentialsException;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use App\Models\Drive;

class PeoplesRepository extends BaseRepository {


    public function __construct(private Peoples $entity)
    {
        parent::__construct($entity);
    }

    /**
     * Summary of getAll
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getAll(): Collection {
        return $this->relationship($this->entity, ['drive'])->get();
    }

    /**
     * Summary of findWhere
     * @param string $column
     * @param string $value
     * @return Collection
     */
    public function findWhere(string $column, string $value): Collection
    {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Summary of paginate
     * @param int $totalPage
     * @return \Illuminate\Pagination\LengthAwarePaginator
     */
    public function paginate(int $totalPage = 10): LengthAwarePaginator
    {
        return parent::paginate($totalPage); // TODO: Change the autogenerated stub
    }

     /**
      * Summary of findById
      * @param int $id
      * @return object
      */
    public function findById(int $id): object
    {
        return $this->relationship($this->entity, ['drive'])->findOrFail($id);
    }

    /**
     * Summary of relationship
     * @param mixed $entity
     * @param mixed $relations
     */
    private function relationship($entity, $relations = []) {

        return $entity->with($relations);
    }

    /**
     * Summary of store
     * @param array $data
     * @return void
     */
    public function store(array $data): void {

        try {
            DB::beginTransaction();
            $people = $this->entity->create($data['people']);
            $data['drive']['people_id'] = $people->id;
            $this->createDrive( $data['drive']);
             DB::commit();
        } catch (\Exception $th) {
           DB::rollBack();
        }

    }

    public function storeFormData(array $data) {
        try {
            DB::beginTransaction();
            $people = $this->entity->create($data['people']);
            if (isset($data['drive']) && !empty($data['drive']['description'])) {
                $data['drive']['people_id'] = $people->id;
                $this->createDrive( $data['drive']);
            }
            DB::commit();
        } catch (\Exception $th) {
           DB::rollBack();
           \Log::error('Erro ao salvar os dados', [$th->getMessage()]);
        }

    }

    public function updateFormData(object $entity, array $data) {
        try {
            DB::beginTransaction();
            $entity->update($data['people']);
            if (isset($data['drive']) && !empty($data['drive']['description'])) {
                $data['people_id'] = $entity->id;
                $this->createDrive( $data);
            }
            DB::commit();
        } catch (\Exception $th) {
            DB::rollBack();
            \Log::error('Erro ao salvar os dados', [$th->getMessage()]);
        }
    }

    /**
     * Summary of createDrive
     * @param mixed $drives
     * @return void
     */
    private function createDrive($drives)
    {
       $drive = Drive::updateOrCreate($drives['drive']);
        DrivePeople::updateOrCreate(
            [
                'drive_id'=> $drive->id,
                'people_id' => $drives['people_id']
            ]);
    }


    public function getPeopleCpf(string $cpf) {

        return$this->relationship($this->entity, ['drive'])->where('cpf','=', $cpf)->first();
    }

}
