<?php

namespace App\Repositories\Core;
use App\Models\FinancialTransactions;
use App\Models\FinancialCategory;
use App\Models\FinancialType;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use App\Models\FinancialStatus;

class RevenueExpenseRepository extends BaseRepository
{

    private $financialCategory;
    private $financialType;
    private $financialStatus;
    /**
     * Summary of __construct
     * @param FinancialTransactions $model
     */
    public function __construct(private FinancialTransactions $model, FinancialCategory $financialCategory, FinancialType $financialType, FinancialStatus $financialStatus)
    {
        parent::__construct($model);
        $this->financialCategory = $financialCategory;
        $this->financialType = $financialType;
        $this->financialStatus = $financialStatus;
    }

    /**
     * Summary of paginate
     * @param int $id
     * @return LengthAwarePaginator
     */
    public function paginate(int $id): LengthAwarePaginator
    {
        return $this->model->where('condominium_id', $id)->paginate(10);
    }

   /**
    * Summary of getAll
    * @return Collection
    */
   public function getAll(): Collection
   {
       return $this->loadRelationships($this->model, ['condominium','financialCategory','financialType','financialStatus'])->get();
   }

    /**
     * Summary of findById
     * @param int $id
     * @return object
     */
    public function findById(int $id): object
    {
         return $this->loadRelationships($this->model, ['condominium','financialCategory','financialType','financialStatus'])->findOrFail($id);
    }

    /**
     * Summary of loadRelationships
     * @param mixed $query
     * @param mixed $relationships
     */
    private function loadRelationships($query, $relationships = [])
    {
        return $query->with(
            $relationships
        );
    }

    /**
     * Summary of findWhere
     * @param string $column
     * @param string $value
     * @return Collection
     */
    public function findWhere(string $column, string $value): Collection
    {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }


    public function store(array $data)
    {
        $status = $this->financialStatus->where('name', 'Pendente')->first();
        $data['financial_status_id'] = $status->id;
        return parent::store($data); // TODO: Change the autogenerated stub
    }


    /**
     * Summary of getCategories
     * @return Collection
     */
    public function getCategories(): Collection
    {
        return $this->financialCategory->select('name','id')->get();
    }

    public function getTypes(): Collection
    {
        return $this->financialType->select('name','id')->get();
    }

    /**
     * Summary of delete
     * @param object $model
     */
    public function delete(object $model)
    {
        return $model->delete();
    }
}
