<?php

namespace App\Repositories\Core;

use App\Models\TypeService;
use App\Repositories\Core\BaseRepository;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;

class TypeServiceRepository extends BaseRepository {

    public function __construct(private TypeService $typeService) {
        parent::__construct($typeService);
    }

    public function getAll(): Collection {
        return $this->typeService->all();
    }

    public function findById(int $id): object {
        return $this->typeService->where('id','=', $id)->first();
    }

    public function findWhere(string $column, string $value): Collection
    {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }

    public function paginate(int $totalPage = 10): LengthAwarePaginator
    {
        return parent::paginate($totalPage); // TODO: Change the autogenerated stub
    }
}
