<?php

namespace App\Repositories\Core;
use App\Models\Visitors;
use App\Exceptions\CredentialsException;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Facades\DB;


class VisitorsRepositories extends BaseRepository {

    public function __construct(private Visitors $visitors)
    {
        parent::__construct($visitors);
    }

    public function getAll(): Collection {
        // return parent::getAll();
        return $this->loadRelationships($this->visitors, ['condominium'])->get();
    }

    public function findWhere(string $column, string $value): Collection {
        return parent::findWhere($column, $value); // TODO: Change the autogenerated stub
    }

    public function paginate(int $totalPage = 10): LengthAwarePaginator   {
        return parent::paginate($totalPage); // TODO: Change the autogenerated stub
    }

    public function getVisitorCondominium() {
        $dados = $this->loadRelationships($this->visitors, ['condominium'])->get();
        // dd($dados);
        return $dados;
    }

    public function store(array $data): void
    {
        try {
            DB::beginTransaction();
            $this->visitors->create($data);
            DB::commit();
        } catch (\Exception $th) {
            DB::rollback();
            throw new CredentialsException($th->getMessage());
        }
    }

    private function loadRelationships($query, $relationships = [])
    {
        return $query->with(
            $relationships
        );
    }
}
