name: CI Pipeline

on:
  push:
    branches: [ feature/trabalhando-pipeline ]
  pull_request:
    branches: [ feature/trabalhando-pipeline ]


join:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: sgc
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: '123456'
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, bcmath, pdo, pdo_pgsql
        tools: composer

    - name: Install backend dependencies
      run: |
        cd backend
        composer Install
        cp .env.example .env
        php artisan key:generate

    - name: Migrate DB
      run: |
        cd backend
        php artisan migrate --force

    - name: Run laravel test
      run: |
        cd backend
        php artisan test

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: build fronted
      run: |
        cd fronted
        npm Install
        npm run build
